# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\02.售后服务\运维\自动化部署资料\页面UI\cloud_data_cut_notng_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_cloud_data_cut_notng_dialog(object):
    def setupUi(self, cloud_data_cut_notng_dialog):
        cloud_data_cut_notng_dialog.setObjectName("cloud_data_cut_notng_dialog")
        cloud_data_cut_notng_dialog.resize(1113, 597)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        cloud_data_cut_notng_dialog.setWindowIcon(icon)
        cloud_data_cut_notng_dialog.setWindowOpacity(2.0)
        self.label = QtWidgets.QLabel(cloud_data_cut_notng_dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 431, 31))
        self.label.setStyleSheet("font: 75 20pt \"Agency FB\";")
        self.label.setObjectName("label")
        self.layoutWidget_2 = QtWidgets.QWidget(cloud_data_cut_notng_dialog)
        self.layoutWidget_2.setGeometry(QtCore.QRect(490, 120, 97, 421))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.one_time_lable = QtWidgets.QLabel(self.layoutWidget_2)
        self.one_time_lable.setObjectName("one_time_lable")
        self.verticalLayout_2.addWidget(self.one_time_lable)
        self.two_time_lable = QtWidgets.QLabel(self.layoutWidget_2)
        self.two_time_lable.setObjectName("two_time_lable")
        self.verticalLayout_2.addWidget(self.two_time_lable)
        self.three_time_lable = QtWidgets.QLabel(self.layoutWidget_2)
        self.three_time_lable.setObjectName("three_time_lable")
        self.verticalLayout_2.addWidget(self.three_time_lable)
        self.four_time_lable = QtWidgets.QLabel(self.layoutWidget_2)
        self.four_time_lable.setObjectName("four_time_lable")
        self.verticalLayout_2.addWidget(self.four_time_lable)
        self.six_time_lable = QtWidgets.QLabel(self.layoutWidget_2)
        self.six_time_lable.setObjectName("six_time_lable")
        self.verticalLayout_2.addWidget(self.six_time_lable)
        self.seven_time_lable = QtWidgets.QLabel(self.layoutWidget_2)
        self.seven_time_lable.setObjectName("seven_time_lable")
        self.verticalLayout_2.addWidget(self.seven_time_lable)
        self.label_2 = QtWidgets.QLabel(cloud_data_cut_notng_dialog)
        self.label_2.setGeometry(QtCore.QRect(640, 5, 54, 21))
        self.label_2.setStyleSheet("font: 75 9pt \"Agency FB\";")
        self.label_2.setObjectName("label_2")
        self.layoutWidget = QtWidgets.QWidget(cloud_data_cut_notng_dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 120, 302, 421))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_4.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_4.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_4.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_4.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_4.addWidget(self.label_21)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_4.addWidget(self.label_23)
        self.line_2 = QtWidgets.QFrame(cloud_data_cut_notng_dialog)
        self.line_2.setGeometry(QtCore.QRect(0, 100, 631, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.layoutWidget_3 = QtWidgets.QWidget(cloud_data_cut_notng_dialog)
        self.layoutWidget_3.setGeometry(QtCore.QRect(30, 120, 45, 421))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_16.setObjectName("label_16")
        self.verticalLayout.addWidget(self.label_16)
        self.label_5 = QtWidgets.QLabel(cloud_data_cut_notng_dialog)
        self.label_5.setGeometry(QtCore.QRect(380, 70, 61, 16))
        self.label_5.setStyleSheet("font: 75 12pt \"Agency FB\";")
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(cloud_data_cut_notng_dialog)
        self.label_4.setGeometry(QtCore.QRect(190, 70, 41, 16))
        self.label_4.setStyleSheet("font: 75 12pt \"Agency FB\";")
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(cloud_data_cut_notng_dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 70, 71, 16))
        self.label_3.setStyleSheet("font: 75 12pt \"Agency FB\";")
        self.label_3.setObjectName("label_3")
        self.scrollArea = QtWidgets.QScrollArea(cloud_data_cut_notng_dialog)
        self.scrollArea.setGeometry(QtCore.QRect(630, 30, 481, 561))
        self.scrollArea.setStyleSheet("background-color:black;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 479, 559))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setGeometry(QtCore.QRect(30, 30, 421, 16))
        self.label_9.setStyleSheet("color:white;")
        self.label_9.setObjectName("label_9")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tempdb_ip_label = QtWidgets.QLabel(cloud_data_cut_notng_dialog)
        self.tempdb_ip_label.setGeometry(QtCore.QRect(100, 70, 81, 16))
        self.tempdb_ip_label.setStyleSheet("font: 75 12pt \"Agency FB\";\n"
"text-decoration: underline;")
        self.tempdb_ip_label.setObjectName("tempdb_ip_label")
        self.tempdb_port_label = QtWidgets.QLabel(cloud_data_cut_notng_dialog)
        self.tempdb_port_label.setGeometry(QtCore.QRect(230, 70, 31, 16))
        self.tempdb_port_label.setStyleSheet("font: 75 12pt \"Agency FB\";\n"
"text-decoration: underline;")
        self.tempdb_port_label.setObjectName("tempdb_port_label")
        self.tempdb_username_label = QtWidgets.QLabel(cloud_data_cut_notng_dialog)
        self.tempdb_username_label.setGeometry(QtCore.QRect(440, 70, 31, 16))
        self.tempdb_username_label.setStyleSheet("font: 75 12pt \"Agency FB\";\n"
"text-decoration: underline;")
        self.tempdb_username_label.setObjectName("tempdb_username_label")
        self.line = QtWidgets.QFrame(cloud_data_cut_notng_dialog)
        self.line.setGeometry(QtCore.QRect(620, 0, 21, 601))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.four_label = QtWidgets.QLabel(cloud_data_cut_notng_dialog)
        self.four_label.setGeometry(QtCore.QRect(410, 330, 41, 78))
        self.four_label.setObjectName("four_label")
        self.three_label = QtWidgets.QLabel(cloud_data_cut_notng_dialog)
        self.three_label.setGeometry(QtCore.QRect(410, 250, 41, 77))
        self.three_label.setObjectName("three_label")
        self.one_label = QtWidgets.QLabel(cloud_data_cut_notng_dialog)
        self.one_label.setGeometry(QtCore.QRect(410, 120, 75, 77))
        self.one_label.setObjectName("one_label")
        self.open_datatool_button = QtWidgets.QPushButton(cloud_data_cut_notng_dialog)
        self.open_datatool_button.setGeometry(QtCore.QRect(390, 210, 41, 23))
        self.open_datatool_button.setObjectName("open_datatool_button")
        self.six_label = QtWidgets.QLabel(cloud_data_cut_notng_dialog)
        self.six_label.setGeometry(QtCore.QRect(410, 400, 41, 77))
        self.six_label.setObjectName("six_label")
        self.seven_label = QtWidgets.QLabel(cloud_data_cut_notng_dialog)
        self.seven_label.setGeometry(QtCore.QRect(410, 490, 41, 41))
        self.seven_label.setObjectName("seven_label")
        self.label_6 = QtWidgets.QLabel(cloud_data_cut_notng_dialog)
        self.label_6.setGeometry(QtCore.QRect(480, 70, 61, 16))
        self.label_6.setStyleSheet("font: 75 12pt \"Agency FB\";")
        self.label_6.setObjectName("label_6")
        self.tempdb_pwd_label = QtWidgets.QLabel(cloud_data_cut_notng_dialog)
        self.tempdb_pwd_label.setGeometry(QtCore.QRect(520, 70, 41, 16))
        self.tempdb_pwd_label.setStyleSheet("font: 75 12pt \"Agency FB\";\n"
"text-decoration: underline;")
        self.tempdb_pwd_label.setObjectName("tempdb_pwd_label")
        self.tempdb_name_label = QtWidgets.QLabel(cloud_data_cut_notng_dialog)
        self.tempdb_name_label.setGeometry(QtCore.QRect(320, 70, 41, 16))
        self.tempdb_name_label.setStyleSheet("font: 75 12pt \"Agency FB\";\n"
"text-decoration: underline;")
        self.tempdb_name_label.setObjectName("tempdb_name_label")
        self.label_7 = QtWidgets.QLabel(cloud_data_cut_notng_dialog)
        self.label_7.setGeometry(QtCore.QRect(280, 70, 41, 16))
        self.label_7.setStyleSheet("font: 75 12pt \"Agency FB\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(cloud_data_cut_notng_dialog)
        self.label_8.setGeometry(QtCore.QRect(460, 20, 71, 16))
        self.label_8.setStyleSheet("font: 75 12pt \"Agency FB\";")
        self.label_8.setObjectName("label_8")
        self.tenant_code_label = QtWidgets.QLabel(cloud_data_cut_notng_dialog)
        self.tenant_code_label.setGeometry(QtCore.QRect(540, 20, 81, 16))
        self.tenant_code_label.setStyleSheet("font: 75 12pt \"Agency FB\";\n"
"text-decoration: underline;")
        self.tenant_code_label.setObjectName("tenant_code_label")
        self.three_time_lable_2 = QtWidgets.QLabel(cloud_data_cut_notng_dialog)
        self.three_time_lable_2.setGeometry(QtCore.QRect(780, 530, 95, 64))
        self.three_time_lable_2.setObjectName("three_time_lable_2")
        self.three_time_lable_3 = QtWidgets.QLabel(cloud_data_cut_notng_dialog)
        self.three_time_lable_3.setGeometry(QtCore.QRect(860, 530, 95, 64))
        self.three_time_lable_3.setObjectName("three_time_lable_3")
        self.next_button = QtWidgets.QPushButton(cloud_data_cut_notng_dialog)
        self.next_button.setGeometry(QtCore.QRect(440, 210, 41, 23))
        self.next_button.setObjectName("next_button")

        self.retranslateUi(cloud_data_cut_notng_dialog)
        QtCore.QMetaObject.connectSlotsByName(cloud_data_cut_notng_dialog)

    def retranslateUi(self, cloud_data_cut_notng_dialog):
        _translate = QtCore.QCoreApplication.translate
        cloud_data_cut_notng_dialog.setWindowTitle(_translate("cloud_data_cut_notng_dialog", "云票务数据迁移(源：非火烈鸟)"))
        self.label.setText(_translate("cloud_data_cut_notng_dialog", "深圳泰久电影院（88888888）"))
        self.one_time_lable.setText(_translate("cloud_data_cut_notng_dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">耗时：100秒</span></p></body></html>"))
        self.two_time_lable.setText(_translate("cloud_data_cut_notng_dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.three_time_lable.setText(_translate("cloud_data_cut_notng_dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">耗时：100秒</span></p></body></html>"))
        self.four_time_lable.setText(_translate("cloud_data_cut_notng_dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">耗时：100秒</span></p></body></html>"))
        self.six_time_lable.setText(_translate("cloud_data_cut_notng_dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">耗时：100秒</span></p></body></html>"))
        self.seven_time_lable.setText(_translate("cloud_data_cut_notng_dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">耗时：100秒</span></p></body></html>"))
        self.label_2.setText(_translate("cloud_data_cut_notng_dialog", "控制台"))
        self.label_17.setText(_translate("cloud_data_cut_notng_dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">创建并连接临时库</span></p></body></html>"))
        self.label_18.setText(_translate("cloud_data_cut_notng_dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">迁移数据到临时库</span></p></body></html>"))
        self.label_19.setText(_translate("cloud_data_cut_notng_dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">数据从临时库迁移云票务正式库</span></p></body></html>"))
        self.label_20.setText(_translate("cloud_data_cut_notng_dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">功能检测</span></p></body></html>"))
        self.label_21.setText(_translate("cloud_data_cut_notng_dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">备份并删除临时库</span></p></body></html>"))
        self.label_23.setText(_translate("cloud_data_cut_notng_dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">迁移完成\n"
"</span></p></body></html>"))
        self.label_10.setText(_translate("cloud_data_cut_notng_dialog", "<html><head/><body><p><img src=\"res/num_1.png\"/></p></body></html>"))
        self.label_11.setText(_translate("cloud_data_cut_notng_dialog", "<html><head/><body><p><img src=\"res/num_2.png\"/></p></body></html>"))
        self.label_12.setText(_translate("cloud_data_cut_notng_dialog", "<html><head/><body><p><img src=\"res/num_3.png\"/></p></body></html>"))
        self.label_13.setText(_translate("cloud_data_cut_notng_dialog", "<html><head/><body><p><img src=\"res/num_4.png\"/></p></body></html>"))
        self.label_15.setText(_translate("cloud_data_cut_notng_dialog", "<html><head/><body><p><img src=\"res/num_5.png\"/></p></body></html>"))
        self.label_16.setText(_translate("cloud_data_cut_notng_dialog", "<html><head/><body><p><img src=\"res/num_6.png\"/></p></body></html>"))
        self.label_5.setText(_translate("cloud_data_cut_notng_dialog", "用户名："))
        self.label_4.setText(_translate("cloud_data_cut_notng_dialog", "端口："))
        self.label_3.setText(_translate("cloud_data_cut_notng_dialog", "临时库IP："))
        self.label_9.setText(_translate("cloud_data_cut_notng_dialog", "显示操作日志"))
        self.tempdb_ip_label.setText(_translate("cloud_data_cut_notng_dialog", "192.169.112.346"))
        self.tempdb_port_label.setText(_translate("cloud_data_cut_notng_dialog", "3306"))
        self.tempdb_username_label.setText(_translate("cloud_data_cut_notng_dialog", "root"))
        self.four_label.setText(_translate("cloud_data_cut_notng_dialog", "<html><head/><body><p><img src=\"res/duihao.png\"/></p></body></html>"))
        self.three_label.setText(_translate("cloud_data_cut_notng_dialog", "<html><head/><body><p><img src=\"res/duihao.png\"/></p></body></html>"))
        self.one_label.setText(_translate("cloud_data_cut_notng_dialog", "<html><head/><body><p><img src=\"res/duihao.png\"/></p></body></html>"))
        self.open_datatool_button.setText(_translate("cloud_data_cut_notng_dialog", "迁移"))
        self.six_label.setText(_translate("cloud_data_cut_notng_dialog", "<html><head/><body><p><img src=\"res/cuo.png\"/></p></body></html>"))
        self.seven_label.setText(_translate("cloud_data_cut_notng_dialog", "<html><head/><body><p><img src=\"res/cuo.png\"/></p></body></html>"))
        self.label_6.setText(_translate("cloud_data_cut_notng_dialog", "密码："))
        self.tempdb_pwd_label.setText(_translate("cloud_data_cut_notng_dialog", "ngV523"))
        self.tempdb_name_label.setText(_translate("cloud_data_cut_notng_dialog", "SCTS"))
        self.label_7.setText(_translate("cloud_data_cut_notng_dialog", "库名："))
        self.label_8.setText(_translate("cloud_data_cut_notng_dialog", "租户编码："))
        self.tenant_code_label.setText(_translate("cloud_data_cut_notng_dialog", "HLDY"))
        self.three_time_lable_2.setText(_translate("cloud_data_cut_notng_dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">耗时：100秒</span></p></body></html>"))
        self.three_time_lable_3.setText(_translate("cloud_data_cut_notng_dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">耗时：100秒</span></p></body></html>"))
        self.next_button.setText(_translate("cloud_data_cut_notng_dialog", "完成"))
