# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\02.售后服务\运维\自动化部署资料\页面UI\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(729, 317)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(330, 0, 71, 31))
        self.label.setAutoFillBackground(True)
        self.label.setStyleSheet("font: 75 14pt \"Agency FB\";")
        self.label.setObjectName("label")
        self.ng_install_Button = QtWidgets.QPushButton(self.centralwidget)
        self.ng_install_Button.setGeometry(QtCore.QRect(70, 50, 161, 61))
        self.ng_install_Button.setStyleSheet("font: 75 16pt \"Agency FB\";\n"
"")
        self.ng_install_Button.setObjectName("ng_install_Button")
        self.data_transfer_Button = QtWidgets.QPushButton(self.centralwidget)
        self.data_transfer_Button.setGeometry(QtCore.QRect(290, 50, 161, 61))
        self.data_transfer_Button.setStyleSheet("font: 75 16pt \"Agency FB\";")
        self.data_transfer_Button.setObjectName("data_transfer_Button")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.setGeometry(QtCore.QRect(500, 50, 161, 61))
        self.pushButton_3.setStyleSheet("font: 75 14pt \"Agency FB\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(330, 150, 71, 31))
        self.label_2.setAutoFillBackground(True)
        self.label_2.setStyleSheet("font: 75 14pt \"Agency FB\";")
        self.label_2.setObjectName("label_2")
        self.ng_cloud_Button = QtWidgets.QPushButton(self.centralwidget)
        self.ng_cloud_Button.setGeometry(QtCore.QRect(70, 200, 161, 61))
        self.ng_cloud_Button.setStyleSheet("font: 75 16pt \"Agency FB\";")
        self.ng_cloud_Button.setObjectName("ng_cloud_Button")
        self.ng_cloud_cut_Button = QtWidgets.QPushButton(self.centralwidget)
        self.ng_cloud_cut_Button.setGeometry(QtCore.QRect(290, 200, 161, 61))
        self.ng_cloud_cut_Button.setStyleSheet("font: 75 16pt \"Agency FB\";")
        self.ng_cloud_cut_Button.setObjectName("ng_cloud_cut_Button")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 140, 731, 16))
        self.line.setStyleSheet("")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.ng_install_Button.raise_()
        self.data_transfer_Button.raise_()
        self.pushButton_3.raise_()
        self.label_2.raise_()
        self.ng_cloud_Button.raise_()
        self.ng_cloud_cut_Button.raise_()
        self.label.raise_()
        self.line.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 729, 23))
        self.menubar.setObjectName("menubar")
        self.pkcode_menu = QtWidgets.QMenu(self.menubar)
        self.pkcode_menu.setObjectName("pkcode_menu")
        self.menu_7 = QtWidgets.QMenu(self.pkcode_menu)
        self.menu_7.setObjectName("menu_7")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_UK = QtWidgets.QMenu(self.menu_3)
        self.menu_UK.setObjectName("menu_UK")
        self.menu_2 = QtWidgets.QMenu(self.menu_3)
        self.menu_2.setObjectName("menu_2")
        self.menu_6 = QtWidgets.QMenu(self.menu_3)
        self.menu_6.setObjectName("menu_6")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menubar)
        self.menu_5.setObjectName("menu_5")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menber_data_check_action = QtWidgets.QAction(MainWindow)
        self.menber_data_check_action.setObjectName("menber_data_check_action")
        self.certificate_data_check_action = QtWidgets.QAction(MainWindow)
        self.certificate_data_check_action.setObjectName("certificate_data_check_action")
        self.goods_data_check_action = QtWidgets.QAction(MainWindow)
        self.goods_data_check_action.setObjectName("goods_data_check_action")
        self.global_set_action = QtWidgets.QAction(MainWindow)
        self.global_set_action.setObjectName("global_set_action")
        self.check_port_action = QtWidgets.QAction(MainWindow)
        self.check_port_action.setObjectName("check_port_action")
        self.check_disk_action = QtWidgets.QAction(MainWindow)
        self.check_disk_action.setObjectName("check_disk_action")
        self.ng_check_uk_action = QtWidgets.QAction(MainWindow)
        self.ng_check_uk_action.setObjectName("ng_check_uk_action")
        self.ng_check_login_action = QtWidgets.QAction(MainWindow)
        self.ng_check_login_action.setObjectName("ng_check_login_action")
        self.ng_check_all_action = QtWidgets.QAction(MainWindow)
        self.ng_check_all_action.setObjectName("ng_check_all_action")
        self.cloud_check_uk_action = QtWidgets.QAction(MainWindow)
        self.cloud_check_uk_action.setObjectName("cloud_check_uk_action")
        self.cloud_check_login_action = QtWidgets.QAction(MainWindow)
        self.cloud_check_login_action.setObjectName("cloud_check_login_action")
        self.cloud_check_all_action = QtWidgets.QAction(MainWindow)
        self.cloud_check_all_action.setObjectName("cloud_check_all_action")
        self.ng_getpk_action = QtWidgets.QAction(MainWindow)
        self.ng_getpk_action.setObjectName("ng_getpk_action")
        self.cloud_getpk_action = QtWidgets.QAction(MainWindow)
        self.cloud_getpk_action.setObjectName("cloud_getpk_action")
        self.open_weichat_action = QtWidgets.QAction(MainWindow)
        self.open_weichat_action.setObjectName("open_weichat_action")
        self.open_aipay_action = QtWidgets.QAction(MainWindow)
        self.open_aipay_action.setObjectName("open_aipay_action")
        self.menu_7.addAction(self.ng_getpk_action)
        self.menu_7.addAction(self.cloud_getpk_action)
        self.pkcode_menu.addAction(self.menu_7.menuAction())
        self.menu_UK.addAction(self.ng_check_uk_action)
        self.menu_UK.addAction(self.cloud_check_uk_action)
        self.menu_2.addAction(self.ng_check_login_action)
        self.menu_2.addAction(self.cloud_check_login_action)
        self.menu_6.addAction(self.ng_check_all_action)
        self.menu_6.addAction(self.cloud_check_all_action)
        self.menu_3.addAction(self.menu_UK.menuAction())
        self.menu_3.addAction(self.menu_2.menuAction())
        self.menu_3.addAction(self.check_port_action)
        self.menu_3.addAction(self.check_disk_action)
        self.menu_3.addAction(self.menu_6.menuAction())
        self.menu_4.addAction(self.open_weichat_action)
        self.menu_4.addAction(self.open_aipay_action)
        self.menu_5.addAction(self.menber_data_check_action)
        self.menu_5.addAction(self.certificate_data_check_action)
        self.menu_5.addAction(self.goods_data_check_action)
        self.menu.addAction(self.global_set_action)
        self.menubar.addAction(self.pkcode_menu.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MAD"))
        self.label.setText(_translate("MainWindow", "火烈鸟"))
        self.ng_install_Button.setText(_translate("MainWindow", "火烈鸟安装"))
        self.data_transfer_Button.setText(_translate("MainWindow", "数据导入火烈鸟"))
        self.pushButton_3.setText(_translate("MainWindow", "采集工具(未开放)"))
        self.label_2.setText(_translate("MainWindow", "云票务"))
        self.ng_cloud_Button.setText(_translate("MainWindow", "云票务地面安装"))
        self.ng_cloud_cut_Button.setText(_translate("MainWindow", "数据导入云票务"))
        self.pkcode_menu.setTitle(_translate("MainWindow", "PK码和网络账号"))
        self.menu_7.setTitle(_translate("MainWindow", "获取"))
        self.menu_3.setTitle(_translate("MainWindow", "检测"))
        self.menu_UK.setTitle(_translate("MainWindow", "检测UK连接"))
        self.menu_2.setTitle(_translate("MainWindow", "检测系统登录"))
        self.menu_6.setTitle(_translate("MainWindow", "以上全部"))
        self.menu_4.setTitle(_translate("MainWindow", "第三方支付"))
        self.menu_5.setTitle(_translate("MainWindow", "导入数据验证"))
        self.menu.setTitle(_translate("MainWindow", "设置"))
        self.menber_data_check_action.setText(_translate("MainWindow", "会员数据验证"))
        self.certificate_data_check_action.setText(_translate("MainWindow", "券数据验证"))
        self.goods_data_check_action.setText(_translate("MainWindow", "卖品数据验证"))
        self.global_set_action.setText(_translate("MainWindow", "服务器远程设置"))
        self.check_port_action.setText(_translate("MainWindow", "相关端口检测"))
        self.check_disk_action.setText(_translate("MainWindow", "服务器硬件检测"))
        self.ng_check_uk_action.setText(_translate("MainWindow", "火烈鸟"))
        self.ng_check_login_action.setText(_translate("MainWindow", "火烈鸟"))
        self.ng_check_all_action.setText(_translate("MainWindow", "火烈鸟"))
        self.cloud_check_uk_action.setText(_translate("MainWindow", "云票务"))
        self.cloud_check_login_action.setText(_translate("MainWindow", "云票务"))
        self.cloud_check_all_action.setText(_translate("MainWindow", "云票务"))
        self.ng_getpk_action.setText(_translate("MainWindow", "火烈鸟"))
        self.cloud_getpk_action.setText(_translate("MainWindow", "云票务"))
        self.open_weichat_action.setText(_translate("MainWindow", "微信"))
        self.open_aipay_action.setText(_translate("MainWindow", "支付宝"))
