# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\02.售后服务\运维\自动化部署资料\页面UI\ng_new_setting_dailog.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ng_new_setting_dialog(object):
    def setupUi(self, ng_new_setting_dialog):
        ng_new_setting_dialog.setObjectName("ng_new_setting_dialog")
        ng_new_setting_dialog.resize(327, 333)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ng_new_setting_dialog.setWindowIcon(icon)
        ng_new_setting_dialog.setStyleSheet("")
        self.serverip_text = QtWidgets.QLineEdit(ng_new_setting_dialog)
        self.serverip_text.setGeometry(QtCore.QRect(110, 100, 151, 20))
        self.serverip_text.setObjectName("serverip_text")
        self.label = QtWidgets.QLabel(ng_new_setting_dialog)
        self.label.setGeometry(QtCore.QRect(50, 100, 54, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(ng_new_setting_dialog)
        self.label_2.setGeometry(QtCore.QRect(60, 180, 41, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(ng_new_setting_dialog)
        self.label_3.setGeometry(QtCore.QRect(50, 210, 51, 21))
        self.label_3.setObjectName("label_3")
        self.username_text = QtWidgets.QLineEdit(ng_new_setting_dialog)
        self.username_text.setGeometry(QtCore.QRect(110, 180, 151, 20))
        self.username_text.setObjectName("username_text")
        self.password_text = QtWidgets.QLineEdit(ng_new_setting_dialog)
        self.password_text.setGeometry(QtCore.QRect(110, 210, 151, 20))
        self.password_text.setObjectName("password_text")
        self.closeButton = QtWidgets.QPushButton(ng_new_setting_dialog)
        self.closeButton.setGeometry(QtCore.QRect(80, 290, 75, 23))
        self.closeButton.setObjectName("closeButton")
        self.nextButton = QtWidgets.QPushButton(ng_new_setting_dialog)
        self.nextButton.setGeometry(QtCore.QRect(190, 290, 75, 23))
        self.nextButton.setObjectName("nextButton")
        self.label_5 = QtWidgets.QLabel(ng_new_setting_dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 250, 54, 12))
        self.label_5.setObjectName("label_5")
        self.radioButton = QtWidgets.QRadioButton(ng_new_setting_dialog)
        self.radioButton.setGeometry(QtCore.QRect(80, 250, 51, 16))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(ng_new_setting_dialog)
        self.radioButton_2.setGeometry(QtCore.QRect(140, 250, 51, 16))
        self.radioButton_2.setObjectName("radioButton_2")
        self.delaytime_text = QtWidgets.QLineEdit(ng_new_setting_dialog)
        self.delaytime_text.setEnabled(True)
        self.delaytime_text.setGeometry(QtCore.QRect(190, 250, 51, 20))
        self.delaytime_text.setDragEnabled(False)
        self.delaytime_text.setClearButtonEnabled(False)
        self.delaytime_text.setObjectName("delaytime_text")
        self.label_6 = QtWidgets.QLabel(ng_new_setting_dialog)
        self.label_6.setEnabled(True)
        self.label_6.setGeometry(QtCore.QRect(250, 250, 81, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(ng_new_setting_dialog)
        self.label_7.setGeometry(QtCore.QRect(50, 20, 54, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(ng_new_setting_dialog)
        self.label_8.setGeometry(QtCore.QRect(50, 60, 54, 21))
        self.label_8.setObjectName("label_8")
        self.ciname_name_text = QtWidgets.QLineEdit(ng_new_setting_dialog)
        self.ciname_name_text.setGeometry(QtCore.QRect(110, 20, 151, 20))
        self.ciname_name_text.setObjectName("ciname_name_text")
        self.ciname_code_text = QtWidgets.QLineEdit(ng_new_setting_dialog)
        self.ciname_code_text.setGeometry(QtCore.QRect(110, 60, 151, 20))
        self.ciname_code_text.setObjectName("ciname_code_text")
        self.port_text = QtWidgets.QLineEdit(ng_new_setting_dialog)
        self.port_text.setGeometry(QtCore.QRect(110, 140, 151, 20))
        self.port_text.setObjectName("port_text")
        self.label_9 = QtWidgets.QLabel(ng_new_setting_dialog)
        self.label_9.setGeometry(QtCore.QRect(70, 140, 41, 21))
        self.label_9.setObjectName("label_9")

        self.retranslateUi(ng_new_setting_dialog)
        QtCore.QMetaObject.connectSlotsByName(ng_new_setting_dialog)

    def retranslateUi(self, ng_new_setting_dialog):
        _translate = QtCore.QCoreApplication.translate
        ng_new_setting_dialog.setWindowTitle(_translate("ng_new_setting_dialog", "火烈鸟新装设置"))
        ng_new_setting_dialog.setWhatsThis(_translate("ng_new_setting_dialog", "<html><head/><body><p>设置新装的服务器地址及自动新装时间</p></body></html>"))
        self.label.setText(_translate("ng_new_setting_dialog", "服务器IP："))
        self.label_2.setText(_translate("ng_new_setting_dialog", "用户名："))
        self.label_3.setText(_translate("ng_new_setting_dialog", "密   码："))
        self.username_text.setText(_translate("ng_new_setting_dialog", "root"))
        self.closeButton.setText(_translate("ng_new_setting_dialog", "关闭"))
        self.nextButton.setText(_translate("ng_new_setting_dialog", "下一步"))
        self.label_5.setText(_translate("ng_new_setting_dialog", "触发时间："))
        self.radioButton.setText(_translate("ng_new_setting_dialog", "立即"))
        self.radioButton_2.setText(_translate("ng_new_setting_dialog", "定时"))
        self.label_6.setText(_translate("ng_new_setting_dialog", "分钟后执行"))
        self.label_7.setText(_translate("ng_new_setting_dialog", "影院名称："))
        self.label_8.setText(_translate("ng_new_setting_dialog", "影院编码："))
        self.port_text.setText(_translate("ng_new_setting_dialog", "36566"))
        self.label_9.setText(_translate("ng_new_setting_dialog", "端口："))
