# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\02.售后服务\运维\自动化部署资料\页面UI\cloud_data_cut_ng_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_cloud_data_cut_ng_dialog(object):
    def setupUi(self, cloud_data_cut_ng_dialog):
        cloud_data_cut_ng_dialog.setObjectName("cloud_data_cut_ng_dialog")
        cloud_data_cut_ng_dialog.resize(1111, 672)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        cloud_data_cut_ng_dialog.setWindowIcon(icon)
        self.label_3 = QtWidgets.QLabel(cloud_data_cut_ng_dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 71, 16))
        self.label_3.setStyleSheet("font: 75 12pt \"Agency FB\";")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(cloud_data_cut_ng_dialog)
        self.label_2.setGeometry(QtCore.QRect(630, 5, 54, 21))
        self.label_2.setStyleSheet("font: 75 9pt \"Agency FB\";")
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(cloud_data_cut_ng_dialog)
        self.label_6.setGeometry(QtCore.QRect(450, 130, 61, 16))
        self.label_6.setStyleSheet("font: 75 12pt \"Agency FB\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(cloud_data_cut_ng_dialog)
        self.label_7.setGeometry(QtCore.QRect(270, 130, 41, 16))
        self.label_7.setStyleSheet("font: 75 12pt \"Agency FB\";")
        self.label_7.setObjectName("label_7")
        self.label_4 = QtWidgets.QLabel(cloud_data_cut_ng_dialog)
        self.label_4.setGeometry(QtCore.QRect(180, 130, 41, 16))
        self.label_4.setStyleSheet("font: 75 12pt \"Agency FB\";")
        self.label_4.setObjectName("label_4")
        self.scrollArea = QtWidgets.QScrollArea(cloud_data_cut_ng_dialog)
        self.scrollArea.setGeometry(QtCore.QRect(620, 30, 481, 641))
        self.scrollArea.setStyleSheet("background-color:black;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 479, 639))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setGeometry(QtCore.QRect(30, 30, 421, 16))
        self.label_9.setStyleSheet("color:white;")
        self.label_9.setObjectName("label_9")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label_5 = QtWidgets.QLabel(cloud_data_cut_ng_dialog)
        self.label_5.setGeometry(QtCore.QRect(350, 130, 61, 16))
        self.label_5.setStyleSheet("font: 75 12pt \"Agency FB\";")
        self.label_5.setObjectName("label_5")
        self.tempdb_ip_label = QtWidgets.QLabel(cloud_data_cut_ng_dialog)
        self.tempdb_ip_label.setGeometry(QtCore.QRect(90, 130, 81, 16))
        self.tempdb_ip_label.setStyleSheet("font: 75 12pt \"Agency FB\";\n"
"text-decoration: underline;")
        self.tempdb_ip_label.setObjectName("tempdb_ip_label")
        self.layoutWidget = QtWidgets.QWidget(cloud_data_cut_ng_dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 190, 322, 441))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        self.label_17.setStyleSheet("font: 75 12pt \"Agency FB\";")
        self.label_17.setObjectName("label_17")
        self.verticalLayout_4.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_4.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_4.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_4.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_4.addWidget(self.label_21)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_4.addWidget(self.label_24)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_4.addWidget(self.label_23)
        self.label_8 = QtWidgets.QLabel(cloud_data_cut_ng_dialog)
        self.label_8.setGeometry(QtCore.QRect(450, 20, 71, 16))
        self.label_8.setStyleSheet("font: 75 12pt \"Agency FB\";")
        self.label_8.setObjectName("label_8")
        self.line = QtWidgets.QFrame(cloud_data_cut_ng_dialog)
        self.line.setGeometry(QtCore.QRect(610, 0, 21, 671))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layoutWidget_2 = QtWidgets.QWidget(cloud_data_cut_ng_dialog)
        self.layoutWidget_2.setGeometry(QtCore.QRect(480, 190, 97, 441))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.one_time_lable = QtWidgets.QLabel(self.layoutWidget_2)
        self.one_time_lable.setObjectName("one_time_lable")
        self.verticalLayout_2.addWidget(self.one_time_lable)
        self.three_time_lable_3 = QtWidgets.QLabel(self.layoutWidget_2)
        self.three_time_lable_3.setObjectName("three_time_lable_3")
        self.verticalLayout_2.addWidget(self.three_time_lable_3)
        self.three_time_lable_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.three_time_lable_2.setObjectName("three_time_lable_2")
        self.verticalLayout_2.addWidget(self.three_time_lable_2)
        self.three_time_lable = QtWidgets.QLabel(self.layoutWidget_2)
        self.three_time_lable.setObjectName("three_time_lable")
        self.verticalLayout_2.addWidget(self.three_time_lable)
        self.four_time_lable = QtWidgets.QLabel(self.layoutWidget_2)
        self.four_time_lable.setObjectName("four_time_lable")
        self.verticalLayout_2.addWidget(self.four_time_lable)
        self.six_time_lable = QtWidgets.QLabel(self.layoutWidget_2)
        self.six_time_lable.setObjectName("six_time_lable")
        self.verticalLayout_2.addWidget(self.six_time_lable)
        self.seven_time_lable = QtWidgets.QLabel(self.layoutWidget_2)
        self.seven_time_lable.setObjectName("seven_time_lable")
        self.verticalLayout_2.addWidget(self.seven_time_lable)
        self.tenant_code_label = QtWidgets.QLabel(cloud_data_cut_ng_dialog)
        self.tenant_code_label.setGeometry(QtCore.QRect(530, 20, 81, 16))
        self.tenant_code_label.setStyleSheet("font: 75 12pt \"Agency FB\";\n"
"text-decoration: underline;")
        self.tenant_code_label.setObjectName("tenant_code_label")
        self.tempdb_username_label = QtWidgets.QLabel(cloud_data_cut_ng_dialog)
        self.tempdb_username_label.setGeometry(QtCore.QRect(410, 130, 31, 16))
        self.tempdb_username_label.setStyleSheet("font: 75 12pt \"Agency FB\";\n"
"text-decoration: underline;")
        self.tempdb_username_label.setObjectName("tempdb_username_label")
        self.tempdb_port_label = QtWidgets.QLabel(cloud_data_cut_ng_dialog)
        self.tempdb_port_label.setGeometry(QtCore.QRect(220, 130, 31, 16))
        self.tempdb_port_label.setStyleSheet("font: 75 12pt \"Agency FB\";\n"
"text-decoration: underline;")
        self.tempdb_port_label.setObjectName("tempdb_port_label")
        self.layoutWidget_3 = QtWidgets.QWidget(cloud_data_cut_ng_dialog)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 190, 56, 441))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_16.setObjectName("label_16")
        self.verticalLayout.addWidget(self.label_16)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.tempdb_pwd_label = QtWidgets.QLabel(cloud_data_cut_ng_dialog)
        self.tempdb_pwd_label.setGeometry(QtCore.QRect(490, 130, 41, 16))
        self.tempdb_pwd_label.setStyleSheet("font: 75 12pt \"Agency FB\";\n"
"text-decoration: underline;")
        self.tempdb_pwd_label.setObjectName("tempdb_pwd_label")
        self.line_2 = QtWidgets.QFrame(cloud_data_cut_ng_dialog)
        self.line_2.setGeometry(QtCore.QRect(-10, 170, 631, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label = QtWidgets.QLabel(cloud_data_cut_ng_dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 431, 31))
        self.label.setStyleSheet("font: 75 20pt \"Agency FB\";")
        self.label.setObjectName("label")
        self.tempdb_name_label = QtWidgets.QLabel(cloud_data_cut_ng_dialog)
        self.tempdb_name_label.setGeometry(QtCore.QRect(310, 130, 41, 16))
        self.tempdb_name_label.setStyleSheet("font: 75 12pt \"Agency FB\";\n"
"text-decoration: underline;")
        self.tempdb_name_label.setObjectName("tempdb_name_label")
        self.ngdb_pwd_label = QtWidgets.QLabel(cloud_data_cut_ng_dialog)
        self.ngdb_pwd_label.setGeometry(QtCore.QRect(510, 80, 41, 16))
        self.ngdb_pwd_label.setStyleSheet("font: 75 12pt \"Agency FB\";\n"
"text-decoration: underline;")
        self.ngdb_pwd_label.setObjectName("ngdb_pwd_label")
        self.ngdb_name_label = QtWidgets.QLabel(cloud_data_cut_ng_dialog)
        self.ngdb_name_label.setGeometry(QtCore.QRect(330, 80, 41, 16))
        self.ngdb_name_label.setStyleSheet("font: 75 12pt \"Agency FB\";\n"
"text-decoration: underline;")
        self.ngdb_name_label.setObjectName("ngdb_name_label")
        self.label_22 = QtWidgets.QLabel(cloud_data_cut_ng_dialog)
        self.label_22.setGeometry(QtCore.QRect(210, 80, 41, 16))
        self.label_22.setStyleSheet("font: 75 12pt \"Agency FB\";")
        self.label_22.setObjectName("label_22")
        self.label_25 = QtWidgets.QLabel(cloud_data_cut_ng_dialog)
        self.label_25.setGeometry(QtCore.QRect(370, 80, 61, 16))
        self.label_25.setStyleSheet("font: 75 12pt \"Agency FB\";")
        self.label_25.setObjectName("label_25")
        self.ngdb_ip_label = QtWidgets.QLabel(cloud_data_cut_ng_dialog)
        self.ngdb_ip_label.setGeometry(QtCore.QRect(120, 80, 81, 16))
        self.ngdb_ip_label.setStyleSheet("font: 75 12pt \"Agency FB\";\n"
"text-decoration: underline;")
        self.ngdb_ip_label.setObjectName("ngdb_ip_label")
        self.ngdb_port_label = QtWidgets.QLabel(cloud_data_cut_ng_dialog)
        self.ngdb_port_label.setGeometry(QtCore.QRect(250, 80, 31, 16))
        self.ngdb_port_label.setStyleSheet("font: 75 12pt \"Agency FB\";\n"
"text-decoration: underline;")
        self.ngdb_port_label.setObjectName("ngdb_port_label")
        self.label_26 = QtWidgets.QLabel(cloud_data_cut_ng_dialog)
        self.label_26.setGeometry(QtCore.QRect(290, 80, 41, 16))
        self.label_26.setStyleSheet("font: 75 12pt \"Agency FB\";")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(cloud_data_cut_ng_dialog)
        self.label_27.setGeometry(QtCore.QRect(10, 80, 111, 16))
        self.label_27.setStyleSheet("font: 75 12pt \"Agency FB\";")
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(cloud_data_cut_ng_dialog)
        self.label_28.setGeometry(QtCore.QRect(470, 80, 61, 16))
        self.label_28.setStyleSheet("font: 75 12pt \"Agency FB\";")
        self.label_28.setObjectName("label_28")
        self.ngdb_username_label = QtWidgets.QLabel(cloud_data_cut_ng_dialog)
        self.ngdb_username_label.setGeometry(QtCore.QRect(430, 80, 31, 16))
        self.ngdb_username_label.setStyleSheet("font: 75 12pt \"Agency FB\";\n"
"text-decoration: underline;")
        self.ngdb_username_label.setObjectName("ngdb_username_label")
        self.layoutWidget1 = QtWidgets.QWidget(cloud_data_cut_ng_dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(420, 190, 39, 441))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.one_label = QtWidgets.QLabel(self.layoutWidget1)
        self.one_label.setObjectName("one_label")
        self.verticalLayout_3.addWidget(self.one_label)
        self.two_label = QtWidgets.QLabel(self.layoutWidget1)
        self.two_label.setObjectName("two_label")
        self.verticalLayout_3.addWidget(self.two_label)
        self.three_label = QtWidgets.QLabel(self.layoutWidget1)
        self.three_label.setObjectName("three_label")
        self.verticalLayout_3.addWidget(self.three_label)
        self.four_label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.four_label_2.setObjectName("four_label_2")
        self.verticalLayout_3.addWidget(self.four_label_2)
        self.four_label = QtWidgets.QLabel(self.layoutWidget1)
        self.four_label.setObjectName("four_label")
        self.verticalLayout_3.addWidget(self.four_label)
        self.five_label = QtWidgets.QLabel(self.layoutWidget1)
        self.five_label.setObjectName("five_label")
        self.verticalLayout_3.addWidget(self.five_label)
        self.six_label = QtWidgets.QLabel(self.layoutWidget1)
        self.six_label.setObjectName("six_label")
        self.verticalLayout_3.addWidget(self.six_label)

        self.retranslateUi(cloud_data_cut_ng_dialog)
        QtCore.QMetaObject.connectSlotsByName(cloud_data_cut_ng_dialog)

    def retranslateUi(self, cloud_data_cut_ng_dialog):
        _translate = QtCore.QCoreApplication.translate
        cloud_data_cut_ng_dialog.setWindowTitle(_translate("cloud_data_cut_ng_dialog", "云票务数据迁移（源：火烈鸟）"))
        self.label_3.setText(_translate("cloud_data_cut_ng_dialog", "临时库IP："))
        self.label_2.setText(_translate("cloud_data_cut_ng_dialog", "控制台"))
        self.label_6.setText(_translate("cloud_data_cut_ng_dialog", "密码："))
        self.label_7.setText(_translate("cloud_data_cut_ng_dialog", "库名："))
        self.label_4.setText(_translate("cloud_data_cut_ng_dialog", "端口："))
        self.label_9.setText(_translate("cloud_data_cut_ng_dialog", "显示操作日志"))
        self.label_5.setText(_translate("cloud_data_cut_ng_dialog", "用户名："))
        self.tempdb_ip_label.setText(_translate("cloud_data_cut_ng_dialog", "192.169.112.346"))
        self.label_17.setText(_translate("cloud_data_cut_ng_dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">备份地面相关表</span></p></body></html>"))
        self.label_18.setText(_translate("cloud_data_cut_ng_dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">云端创建临时库并连接</span></p></body></html>"))
        self.label_19.setText(_translate("cloud_data_cut_ng_dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">上传地面备份库并恢复至新建临时库</span></p></body></html>"))
        self.label_20.setText(_translate("cloud_data_cut_ng_dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">将临时库数据迁移到云票务正式库</span></p></body></html>"))
        self.label_21.setText(_translate("cloud_data_cut_ng_dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">备份并删除临时库</span></p></body></html>"))
        self.label_24.setText(_translate("cloud_data_cut_ng_dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">系统检测\n"
"</span></p></body></html>"))
        self.label_23.setText(_translate("cloud_data_cut_ng_dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">迁移完成\n"
"</span></p></body></html>"))
        self.label_8.setText(_translate("cloud_data_cut_ng_dialog", "租户编码："))
        self.one_time_lable.setText(_translate("cloud_data_cut_ng_dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">耗时：100秒</span></p></body></html>"))
        self.three_time_lable_3.setText(_translate("cloud_data_cut_ng_dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">耗时：100秒</span></p></body></html>"))
        self.three_time_lable_2.setText(_translate("cloud_data_cut_ng_dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">耗时：100秒</span></p></body></html>"))
        self.three_time_lable.setText(_translate("cloud_data_cut_ng_dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">耗时：100秒</span></p></body></html>"))
        self.four_time_lable.setText(_translate("cloud_data_cut_ng_dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">耗时：100秒</span></p></body></html>"))
        self.six_time_lable.setText(_translate("cloud_data_cut_ng_dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">耗时：100秒</span></p></body></html>"))
        self.seven_time_lable.setText(_translate("cloud_data_cut_ng_dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">耗时：100秒</span></p></body></html>"))
        self.tenant_code_label.setText(_translate("cloud_data_cut_ng_dialog", "HLDY"))
        self.tempdb_username_label.setText(_translate("cloud_data_cut_ng_dialog", "root"))
        self.tempdb_port_label.setText(_translate("cloud_data_cut_ng_dialog", "3306"))
        self.label_10.setText(_translate("cloud_data_cut_ng_dialog", "<html><head/><body><p><img src=\"res/num_1.png\"/></p></body></html>"))
        self.label_11.setText(_translate("cloud_data_cut_ng_dialog", "<html><head/><body><p><img src=\"res/num_2.png\"/></p></body></html>"))
        self.label_12.setText(_translate("cloud_data_cut_ng_dialog", "<html><head/><body><p><img src=\"res/num_3.png\"/></p></body></html>"))
        self.label_13.setText(_translate("cloud_data_cut_ng_dialog", "<html><head/><body><p><img src=\"res/num_4.png\"/></p></body></html>"))
        self.label_15.setText(_translate("cloud_data_cut_ng_dialog", "<html><head/><body><p><img src=\"res/num_5.png\"/></p></body></html>"))
        self.label_16.setText(_translate("cloud_data_cut_ng_dialog", "<html><head/><body><p><img src=\"res/num_6.png\"/></p></body></html>"))
        self.label_14.setText(_translate("cloud_data_cut_ng_dialog", "<html><head/><body><p><img src=\"res/num_7.png\"/></p></body></html>"))
        self.tempdb_pwd_label.setText(_translate("cloud_data_cut_ng_dialog", "ngV523"))
        self.label.setText(_translate("cloud_data_cut_ng_dialog", "深圳泰久电影院（88888888）"))
        self.tempdb_name_label.setText(_translate("cloud_data_cut_ng_dialog", "SCTS"))
        self.ngdb_pwd_label.setText(_translate("cloud_data_cut_ng_dialog", "ngV523"))
        self.ngdb_name_label.setText(_translate("cloud_data_cut_ng_dialog", "SCTS"))
        self.label_22.setText(_translate("cloud_data_cut_ng_dialog", "端口："))
        self.label_25.setText(_translate("cloud_data_cut_ng_dialog", "用户名："))
        self.ngdb_ip_label.setText(_translate("cloud_data_cut_ng_dialog", "192.169.112.346"))
        self.ngdb_port_label.setText(_translate("cloud_data_cut_ng_dialog", "3306"))
        self.label_26.setText(_translate("cloud_data_cut_ng_dialog", "库名："))
        self.label_27.setText(_translate("cloud_data_cut_ng_dialog", "火烈鸟数据库IP："))
        self.label_28.setText(_translate("cloud_data_cut_ng_dialog", "密码："))
        self.ngdb_username_label.setText(_translate("cloud_data_cut_ng_dialog", "root"))
        self.one_label.setText(_translate("cloud_data_cut_ng_dialog", "<html><head/><body><p><img src=\"res/duihao.png\"/></p></body></html>"))
        self.two_label.setText(_translate("cloud_data_cut_ng_dialog", "<html><head/><body><p><img src=\"res/duihao.png\"/></p></body></html>"))
        self.three_label.setText(_translate("cloud_data_cut_ng_dialog", "<html><head/><body><p><img src=\"res/duihao.png\"/></p></body></html>"))
        self.four_label_2.setText(_translate("cloud_data_cut_ng_dialog", "<html><head/><body><p><img src=\"res/duihao.png\"/></p></body></html>"))
        self.four_label.setText(_translate("cloud_data_cut_ng_dialog", "<html><head/><body><p><img src=\"res/duihao.png\"/></p></body></html>"))
        self.five_label.setText(_translate("cloud_data_cut_ng_dialog", "<html><head/><body><p><img src=\"res/cuo.png\"/></p></body></html>"))
        self.six_label.setText(_translate("cloud_data_cut_ng_dialog", "<html><head/><body><p><img src=\"res/cuo.png\"/></p></body></html>"))

