# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\02.售后服务\运维\自动化部署资料\页面UI\cloud_new_dailog.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_cloud_new_dailog(object):
    def setupUi(self, cloud_new_dailog):
        cloud_new_dailog.setObjectName("cloud_new_dailog")
        cloud_new_dailog.resize(1118, 593)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        cloud_new_dailog.setWindowIcon(icon)
        self.label_2 = QtWidgets.QLabel(cloud_new_dailog)
        self.label_2.setGeometry(QtCore.QRect(640, 5, 54, 21))
        self.label_2.setStyleSheet("font: 75 9pt \"Agency FB\";")
        self.label_2.setObjectName("label_2")
        self.label_8 = QtWidgets.QLabel(cloud_new_dailog)
        self.label_8.setGeometry(QtCore.QRect(480, 70, 81, 16))
        self.label_8.setStyleSheet("font: 75 12pt \"Agency FB\";\n"
"text-decoration: underline;")
        self.label_8.setObjectName("label_8")
        self.layoutWidget = QtWidgets.QWidget(cloud_new_dailog)
        self.layoutWidget.setGeometry(QtCore.QRect(340, 120, 39, 421))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.one_label = QtWidgets.QLabel(self.layoutWidget)
        self.one_label.setObjectName("one_label")
        self.verticalLayout_3.addWidget(self.one_label)
        self.two_label = QtWidgets.QLabel(self.layoutWidget)
        self.two_label.setObjectName("two_label")
        self.verticalLayout_3.addWidget(self.two_label)
        self.three_label = QtWidgets.QLabel(self.layoutWidget)
        self.three_label.setObjectName("three_label")
        self.verticalLayout_3.addWidget(self.three_label)
        self.four_label = QtWidgets.QLabel(self.layoutWidget)
        self.four_label.setObjectName("four_label")
        self.verticalLayout_3.addWidget(self.four_label)
        self.six_label = QtWidgets.QLabel(self.layoutWidget)
        self.six_label.setObjectName("six_label")
        self.verticalLayout_3.addWidget(self.six_label)
        self.seven_label = QtWidgets.QLabel(self.layoutWidget)
        self.seven_label.setObjectName("seven_label")
        self.verticalLayout_3.addWidget(self.seven_label)
        self.layoutWidget_2 = QtWidgets.QWidget(cloud_new_dailog)
        self.layoutWidget_2.setGeometry(QtCore.QRect(450, 120, 97, 421))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.one_time_lable = QtWidgets.QLabel(self.layoutWidget_2)
        self.one_time_lable.setObjectName("one_time_lable")
        self.verticalLayout_2.addWidget(self.one_time_lable)
        self.two_time_lable = QtWidgets.QLabel(self.layoutWidget_2)
        self.two_time_lable.setObjectName("two_time_lable")
        self.verticalLayout_2.addWidget(self.two_time_lable)
        self.three_time_lable = QtWidgets.QLabel(self.layoutWidget_2)
        self.three_time_lable.setObjectName("three_time_lable")
        self.verticalLayout_2.addWidget(self.three_time_lable)
        self.four_time_lable = QtWidgets.QLabel(self.layoutWidget_2)
        self.four_time_lable.setObjectName("four_time_lable")
        self.verticalLayout_2.addWidget(self.four_time_lable)
        self.six_time_lable = QtWidgets.QLabel(self.layoutWidget_2)
        self.six_time_lable.setObjectName("six_time_lable")
        self.verticalLayout_2.addWidget(self.six_time_lable)
        self.seven_time_lable = QtWidgets.QLabel(self.layoutWidget_2)
        self.seven_time_lable.setObjectName("seven_time_lable")
        self.verticalLayout_2.addWidget(self.seven_time_lable)
        self.scrollArea = QtWidgets.QScrollArea(cloud_new_dailog)
        self.scrollArea.setGeometry(QtCore.QRect(630, 30, 481, 561))
        self.scrollArea.setStyleSheet("background-color:black;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 479, 559))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setGeometry(QtCore.QRect(30, 30, 421, 16))
        self.label_9.setStyleSheet("color:white;")
        self.label_9.setObjectName("label_9")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label_7 = QtWidgets.QLabel(cloud_new_dailog)
        self.label_7.setGeometry(QtCore.QRect(310, 70, 81, 16))
        self.label_7.setStyleSheet("font: 75 12pt \"Agency FB\";\n"
"text-decoration: underline;")
        self.label_7.setObjectName("label_7")
        self.label_4 = QtWidgets.QLabel(cloud_new_dailog)
        self.label_4.setGeometry(QtCore.QRect(230, 70, 71, 16))
        self.label_4.setStyleSheet("font: 75 12pt \"Agency FB\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(cloud_new_dailog)
        self.label_5.setGeometry(QtCore.QRect(410, 70, 61, 16))
        self.label_5.setStyleSheet("font: 75 12pt \"Agency FB\";")
        self.label_5.setObjectName("label_5")
        self.sercerip_label = QtWidgets.QLabel(cloud_new_dailog)
        self.sercerip_label.setGeometry(QtCore.QRect(100, 70, 101, 16))
        self.sercerip_label.setStyleSheet("font: 75 12pt \"Agency FB\";\n"
"text-decoration: underline;")
        self.sercerip_label.setObjectName("sercerip_label")
        self.label_24 = QtWidgets.QLabel(cloud_new_dailog)
        self.label_24.setGeometry(QtCore.QRect(940, 580, 101, 21))
        self.label_24.setObjectName("label_24")
        self.line = QtWidgets.QFrame(cloud_new_dailog)
        self.line.setGeometry(QtCore.QRect(620, 0, 21, 601))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_3 = QtWidgets.QLabel(cloud_new_dailog)
        self.label_3.setGeometry(QtCore.QRect(20, 70, 71, 16))
        self.label_3.setStyleSheet("font: 75 12pt \"Agency FB\";")
        self.label_3.setObjectName("label_3")
        self.line_2 = QtWidgets.QFrame(cloud_new_dailog)
        self.line_2.setGeometry(QtCore.QRect(0, 100, 631, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label = QtWidgets.QLabel(cloud_new_dailog)
        self.label.setGeometry(QtCore.QRect(10, 10, 451, 31))
        self.label.setStyleSheet("font: 75 16pt \"Agency FB\";")
        self.label.setObjectName("label")
        self.layoutWidget_3 = QtWidgets.QWidget(cloud_new_dailog)
        self.layoutWidget_3.setGeometry(QtCore.QRect(30, 120, 45, 421))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_16.setObjectName("label_16")
        self.verticalLayout.addWidget(self.label_16)
        self.tenant_code_label = QtWidgets.QLabel(cloud_new_dailog)
        self.tenant_code_label.setGeometry(QtCore.QRect(540, 20, 81, 16))
        self.tenant_code_label.setStyleSheet("font: 75 12pt \"Agency FB\";\n"
"text-decoration: underline;")
        self.tenant_code_label.setObjectName("tenant_code_label")
        self.label_14 = QtWidgets.QLabel(cloud_new_dailog)
        self.label_14.setGeometry(QtCore.QRect(460, 20, 71, 16))
        self.label_14.setStyleSheet("font: 75 12pt \"Agency FB\";")
        self.label_14.setObjectName("label_14")
        self.layoutWidget1 = QtWidgets.QWidget(cloud_new_dailog)
        self.layoutWidget1.setGeometry(QtCore.QRect(80, 120, 253, 421))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_4.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_4.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_4.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_4.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_4.addWidget(self.label_21)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_4.addWidget(self.label_23)

        self.retranslateUi(cloud_new_dailog)
        QtCore.QMetaObject.connectSlotsByName(cloud_new_dailog)

    def retranslateUi(self, cloud_new_dailog):
        _translate = QtCore.QCoreApplication.translate
        cloud_new_dailog.setWindowTitle(_translate("cloud_new_dailog", "云票务新装"))
        self.label_2.setText(_translate("cloud_new_dailog", "控制台"))
        self.label_8.setText(_translate("cloud_new_dailog", "taijiu,.2018"))
        self.one_label.setText(_translate("cloud_new_dailog", "<html><head/><body><p><img src=\"res/duihao.png\"/></p></body></html>"))
        self.two_label.setText(_translate("cloud_new_dailog", "<html><head/><body><p><img src=\"res/duihao.png\"/></p></body></html>"))
        self.three_label.setText(_translate("cloud_new_dailog", "<html><head/><body><p><img src=\"res/duihao.png\"/></p></body></html>"))
        self.four_label.setText(_translate("cloud_new_dailog", "<html><head/><body><p><img src=\"res/duihao.png\"/></p></body></html>"))
        self.six_label.setText(_translate("cloud_new_dailog", "<html><head/><body><p><img src=\"res/cuo.png\"/></p></body></html>"))
        self.seven_label.setText(_translate("cloud_new_dailog", "<html><head/><body><p><img src=\"res/cuo.png\"/></p></body></html>"))
        self.one_time_lable.setText(_translate("cloud_new_dailog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">耗时：100秒</span></p></body></html>"))
        self.two_time_lable.setText(_translate("cloud_new_dailog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">耗时：100秒</span></p></body></html>"))
        self.three_time_lable.setText(_translate("cloud_new_dailog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">耗时：100秒</span></p></body></html>"))
        self.four_time_lable.setText(_translate("cloud_new_dailog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">耗时：100秒</span></p></body></html>"))
        self.six_time_lable.setText(_translate("cloud_new_dailog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">耗时：100秒</span></p></body></html>"))
        self.seven_time_lable.setText(_translate("cloud_new_dailog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">耗时：100秒</span></p></body></html>"))
        self.label_9.setText(_translate("cloud_new_dailog", "显示操作日志"))
        self.label_7.setText(_translate("cloud_new_dailog", "root"))
        self.label_4.setText(_translate("cloud_new_dailog", "  用户名："))
        self.label_5.setText(_translate("cloud_new_dailog", "    密码："))
        self.sercerip_label.setText(_translate("cloud_new_dailog", "192.169.112.346"))
        self.label_24.setText(_translate("cloud_new_dailog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">耗时：100秒</span></p></body></html>"))
        self.label_3.setText(_translate("cloud_new_dailog", "服务器IP："))
        self.label.setText(_translate("cloud_new_dailog", "<html><head/><body><p>深圳泰久电影院（88888888）<span style=\" color:#ff0000;\">是否自动开通租户？</span></p></body></html>"))
        self.label_10.setText(_translate("cloud_new_dailog", "<html><head/><body><p><img src=\"res/num_1.png\"/></p></body></html>"))
        self.label_11.setText(_translate("cloud_new_dailog", "<html><head/><body><p><img src=\"res/num_2.png\"/></p></body></html>"))
        self.label_12.setText(_translate("cloud_new_dailog", "<html><head/><body><p><img src=\"res/num_3.png\"/></p></body></html>"))
        self.label_13.setText(_translate("cloud_new_dailog", "<html><head/><body><p><img src=\"res/num_4.png\"/></p></body></html>"))
        self.label_15.setText(_translate("cloud_new_dailog", "<html><head/><body><p><img src=\"res/num_5.png\"/></p></body></html>"))
        self.label_16.setText(_translate("cloud_new_dailog", "<html><head/><body><p><img src=\"res/num_6.png\"/></p></body></html>"))
        self.tenant_code_label.setText(_translate("cloud_new_dailog", "HLDY"))
        self.label_14.setText(_translate("cloud_new_dailog", "租户编码："))
        self.label_17.setText(_translate("cloud_new_dailog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">连接服务器</span></p></body></html>"))
        self.label_18.setText(_translate("cloud_new_dailog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">服务器配置优化</span></p></body></html>"))
        self.label_19.setText(_translate("cloud_new_dailog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">下载安装包</span></p></body></html>"))
        self.label_20.setText(_translate("cloud_new_dailog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">云票务地面服务安装</span></p></body></html>"))
        self.label_21.setText(_translate("cloud_new_dailog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">功能检测</span></p></body></html>"))
        self.label_23.setText(_translate("cloud_new_dailog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">安装完成\n"
"</span></p></body></html>"))
