# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\02.售后服务\运维\自动化部署资料\页面UI\cloud_data_cut_setting_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_cloud_data_cut_setting_dialog(object):
    def setupUi(self, cloud_data_cut_setting_dialog):
        cloud_data_cut_setting_dialog.setObjectName("cloud_data_cut_setting_dialog")
        cloud_data_cut_setting_dialog.resize(328, 412)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/qrc/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        cloud_data_cut_setting_dialog.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(cloud_data_cut_setting_dialog)
        self.label.setGeometry(QtCore.QRect(50, 20, 54, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(cloud_data_cut_setting_dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 60, 54, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(cloud_data_cut_setting_dialog)
        self.label_3.setGeometry(QtCore.QRect(50, 100, 54, 21))
        self.label_3.setObjectName("label_3")
        self.tenant_code_text = QtWidgets.QLineEdit(cloud_data_cut_setting_dialog)
        self.tenant_code_text.setGeometry(QtCore.QRect(120, 20, 141, 20))
        self.tenant_code_text.setObjectName("tenant_code_text")
        self.ciname_name_text = QtWidgets.QLineEdit(cloud_data_cut_setting_dialog)
        self.ciname_name_text.setGeometry(QtCore.QRect(120, 60, 141, 20))
        self.ciname_name_text.setObjectName("ciname_name_text")
        self.ciname_code_text = QtWidgets.QLineEdit(cloud_data_cut_setting_dialog)
        self.ciname_code_text.setGeometry(QtCore.QRect(120, 100, 141, 20))
        self.ciname_code_text.setObjectName("ciname_code_text")
        self.closeButton = QtWidgets.QPushButton(cloud_data_cut_setting_dialog)
        self.closeButton.setGeometry(QtCore.QRect(70, 370, 75, 23))
        self.closeButton.setObjectName("closeButton")
        self.nextButton = QtWidgets.QPushButton(cloud_data_cut_setting_dialog)
        self.nextButton.setGeometry(QtCore.QRect(180, 370, 75, 23))
        self.nextButton.setObjectName("nextButton")
        self.label_4 = QtWidgets.QLabel(cloud_data_cut_setting_dialog)
        self.label_4.setGeometry(QtCore.QRect(60, 140, 51, 16))
        self.label_4.setObjectName("label_4")
        self.ng_radioButton = QtWidgets.QRadioButton(cloud_data_cut_setting_dialog)
        self.ng_radioButton.setGeometry(QtCore.QRect(120, 140, 61, 16))
        self.ng_radioButton.setChecked(True)
        self.ng_radioButton.setObjectName("ng_radioButton")
        self.not_ng_radioButton = QtWidgets.QRadioButton(cloud_data_cut_setting_dialog)
        self.not_ng_radioButton.setGeometry(QtCore.QRect(190, 140, 81, 16))
        self.not_ng_radioButton.setObjectName("not_ng_radioButton")
        self.serverip_text = QtWidgets.QLineEdit(cloud_data_cut_setting_dialog)
        self.serverip_text.setGeometry(QtCore.QRect(120, 170, 151, 20))
        self.serverip_text.setObjectName("serverip_text")
        self.password_text = QtWidgets.QLineEdit(cloud_data_cut_setting_dialog)
        self.password_text.setGeometry(QtCore.QRect(120, 330, 151, 20))
        self.password_text.setObjectName("password_text")
        self.username_text = QtWidgets.QLineEdit(cloud_data_cut_setting_dialog)
        self.username_text.setGeometry(QtCore.QRect(120, 290, 151, 20))
        self.username_text.setObjectName("username_text")
        self.port_text = QtWidgets.QLineEdit(cloud_data_cut_setting_dialog)
        self.port_text.setGeometry(QtCore.QRect(120, 250, 151, 20))
        self.port_text.setObjectName("port_text")
        self.label_19 = QtWidgets.QLabel(cloud_data_cut_setting_dialog)
        self.label_19.setGeometry(QtCore.QRect(70, 250, 41, 21))
        self.label_19.setObjectName("label_19")
        self.label_5 = QtWidgets.QLabel(cloud_data_cut_setting_dialog)
        self.label_5.setGeometry(QtCore.QRect(50, 330, 51, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(cloud_data_cut_setting_dialog)
        self.label_6.setGeometry(QtCore.QRect(50, 170, 54, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(cloud_data_cut_setting_dialog)
        self.label_7.setGeometry(QtCore.QRect(60, 290, 41, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(cloud_data_cut_setting_dialog)
        self.label_8.setGeometry(QtCore.QRect(120, 190, 151, 16))
        self.label_8.setStyleSheet("font: 8pt \"Agency FB\";\n"
"color:red;")
        self.label_8.setObjectName("label_8")
        self.dbname_text = QtWidgets.QLineEdit(cloud_data_cut_setting_dialog)
        self.dbname_text.setGeometry(QtCore.QRect(120, 210, 151, 20))
        self.dbname_text.setObjectName("dbname_text")
        self.label_18 = QtWidgets.QLabel(cloud_data_cut_setting_dialog)
        self.label_18.setGeometry(QtCore.QRect(70, 210, 41, 21))
        self.label_18.setObjectName("label_18")

        self.retranslateUi(cloud_data_cut_setting_dialog)
        QtCore.QMetaObject.connectSlotsByName(cloud_data_cut_setting_dialog)

    def retranslateUi(self, cloud_data_cut_setting_dialog):
        _translate = QtCore.QCoreApplication.translate
        cloud_data_cut_setting_dialog.setWindowTitle(_translate("cloud_data_cut_setting_dialog", "云票务数据迁移设置"))
        self.label.setText(_translate("cloud_data_cut_setting_dialog", "租户编码："))
        self.label_2.setText(_translate("cloud_data_cut_setting_dialog", "影院名称："))
        self.label_3.setText(_translate("cloud_data_cut_setting_dialog", "影院编码："))
        self.closeButton.setText(_translate("cloud_data_cut_setting_dialog", "关闭"))
        self.nextButton.setText(_translate("cloud_data_cut_setting_dialog", "下一步"))
        self.label_4.setText(_translate("cloud_data_cut_setting_dialog", "数据源："))
        self.ng_radioButton.setText(_translate("cloud_data_cut_setting_dialog", "火烈鸟"))
        self.not_ng_radioButton.setText(_translate("cloud_data_cut_setting_dialog", "非火烈鸟"))
        self.serverip_text.setText(_translate("cloud_data_cut_setting_dialog", "127.0.0.1"))
        self.password_text.setText(_translate("cloud_data_cut_setting_dialog", "ngV5123"))
        self.username_text.setText(_translate("cloud_data_cut_setting_dialog", "root"))
        self.port_text.setText(_translate("cloud_data_cut_setting_dialog", "3306"))
        self.label_19.setText(_translate("cloud_data_cut_setting_dialog", "端口："))
        self.label_5.setText(_translate("cloud_data_cut_setting_dialog", "密   码："))
        self.label_6.setText(_translate("cloud_data_cut_setting_dialog", "数据库IP："))
        self.label_7.setText(_translate("cloud_data_cut_setting_dialog", "用户名："))
        self.label_8.setText(_translate("cloud_data_cut_setting_dialog", "内网IP，如果远程设置VPN地址"))
        self.dbname_text.setText(_translate("cloud_data_cut_setting_dialog", "SCTS"))
        self.label_18.setText(_translate("cloud_data_cut_setting_dialog", "库名："))


