# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\02.售后服务\运维\自动化部署资料\页面UI\wetcatpay_open_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_wetcatpay_open_dialog(object):
    def setupUi(self, wetcatpay_open_dialog):
        wetcatpay_open_dialog.setObjectName("wetcatpay_open_dialog")
        wetcatpay_open_dialog.resize(400, 381)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        wetcatpay_open_dialog.setWindowIcon(icon)
        self.open_Button = QtWidgets.QPushButton(wetcatpay_open_dialog)
        self.open_Button.setGeometry(QtCore.QRect(130, 260, 75, 23))
        self.open_Button.setObjectName("open_Button")
        self.line = QtWidgets.QFrame(wetcatpay_open_dialog)
        self.line.setGeometry(QtCore.QRect(0, 300, 401, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.message_info_label = QtWidgets.QLabel(wetcatpay_open_dialog)
        self.message_info_label.setGeometry(QtCore.QRect(30, 330, 54, 12))
        self.message_info_label.setObjectName("message_info_label")
        self.layoutWidget = QtWidgets.QWidget(wetcatpay_open_dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 20, 134, 221))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.layoutWidget1 = QtWidgets.QWidget(wetcatpay_open_dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(180, 20, 201, 221))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.appid_text = QtWidgets.QLineEdit(self.layoutWidget1)
        self.appid_text.setObjectName("appid_text")
        self.verticalLayout_2.addWidget(self.appid_text)
        self.appSecet_text = QtWidgets.QLineEdit(self.layoutWidget1)
        self.appSecet_text.setObjectName("appSecet_text")
        self.verticalLayout_2.addWidget(self.appSecet_text)
        self.bussion_code_text = QtWidgets.QLineEdit(self.layoutWidget1)
        self.bussion_code_text.setObjectName("bussion_code_text")
        self.verticalLayout_2.addWidget(self.bussion_code_text)
        self.secret_key_text = QtWidgets.QLineEdit(self.layoutWidget1)
        self.secret_key_text.setObjectName("secret_key_text")
        self.verticalLayout_2.addWidget(self.secret_key_text)
        self.certficate_file = QtWidgets.QLineEdit(self.layoutWidget1)
        self.certficate_file.setObjectName("certficate_file")
        self.verticalLayout_2.addWidget(self.certficate_file)
        self.public_acc_text = QtWidgets.QLineEdit(self.layoutWidget1)
        self.public_acc_text.setObjectName("public_acc_text")
        self.verticalLayout_2.addWidget(self.public_acc_text)
        self.public_pwd_text = QtWidgets.QLineEdit(self.layoutWidget1)
        self.public_pwd_text.setObjectName("public_pwd_text")
        self.verticalLayout_2.addWidget(self.public_pwd_text)

        self.retranslateUi(wetcatpay_open_dialog)
        QtCore.QMetaObject.connectSlotsByName(wetcatpay_open_dialog)

    def retranslateUi(self, wetcatpay_open_dialog):
        _translate = QtCore.QCoreApplication.translate
        wetcatpay_open_dialog.setWindowTitle(_translate("wetcatpay_open_dialog", "开通微信支付"))
        self.open_Button.setText(_translate("wetcatpay_open_dialog", "开通"))
        self.message_info_label.setText(_translate("wetcatpay_open_dialog", "开通成功"))
        self.label.setText(_translate("wetcatpay_open_dialog", "开发者ID（AppID）"))
        self.label_2.setText(_translate("wetcatpay_open_dialog", "开发者密码（AppSecet）"))
        self.label_3.setText(_translate("wetcatpay_open_dialog", "微信支付商户号"))
        self.label_4.setText(_translate("wetcatpay_open_dialog", "商户密钥"))
        self.label_5.setText(_translate("wetcatpay_open_dialog", "P12证书文件"))
        self.label_6.setText(_translate("wetcatpay_open_dialog", "微信公众号账号"))
        self.label_7.setText(_translate("wetcatpay_open_dialog", "微信公众号密码"))